name: Feature Request
description: Suggest an idea for improvement
title: "REQ: "

body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: >
        Please describe what feature you would like to see implemented and descibe which problems the feature would solve.
      placeholder: >
        ...
    validations:
      required: true
