name: Feature Request
description: Suggest an idea for improvement
title: "REQ: "

body:
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve.
      placeholder: >
        ...
    validations:
      required: true
