name: Bug Report
description: Create a report to help us improve
title: "BUG: "
labels: [Bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: >
        What is the nature of the Bug you encountered?
      placeholder: Describe the Bug here.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Expected Bahavior
      description: >
        Please provide a description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducing the example
      description: Please providea a step by step guide on how we can reproduce the error you found.
      placeholder: >
        Steps to reproduce the bug:
        
        1. Go to '...'
        
        2. Click on '....'
        
        3. Scroll down to '....'
        
        4. See error
    validations:
      required: true

