name: doc_pages_workflow
on: push


jobs:

  build_docs_job:
    name: Build docs
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code  
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/checkout@v2
        with: 
          python-version: 3.9
  
      - name: Install dependencies 
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          python -m pip install numpydoc
          
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
      
      
      
      
