name: Python Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint (excluding docs)
        run: |
          pylint --rcfile=.github/workflows/.pylintrc --output="ReWaterGAP_lint.txt" --ignore=docs .

      - name: Upload Pylint report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: pylint-report
          path: ReWaterGAP_lint.txt

      - name: Create Pylint badge
        run: |
          pylint_score=$(tail -n 1 ReWaterGAP_lint.txt | awk '{print $2}')
          echo "Pylint score: $pylint_score"
          echo "Pylint score: $pylint_score" >> result.txt
          
      - name: Upload pylint score as result
        uses: actions/upload-artifact@v2
        with:
          name: pylint-score
          path: result.txt
